sudo: false
language: node_js
node_js:
  - '10'
branches:
  only:
    - master
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email:
    on_success: never
    on_failure: always
install:
  - yarn
script:
  - yarn test:ci
before_deploy:
  - yarn global add netlify-cli
  - yarn build
deploy:
  provider: script
  script: netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --dir ./public --prod
  skip_cleanup: true
  on:
    branch: master
